blank/blank/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
]

blank/home/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url('^$', views.home, name='home'),
]

blank/home/models.py
from django.db import models

# Create your models here.

blank/home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    context = {
        'title': 'Онлайн сервис юридических документов'
    }
    return render(request, 'home/home.html', context)

blank/templates/home/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %}{{title}}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    {% bootstrap_css %}
    {% block css %}
        <!-- Main Style -->
       <link rel="stylesheet" type="text/css" href="{% static 'css/home/main.css' %}">
       
       <!-- Responsive Style -->
       <link rel="stylesheet" type="text/css" href="{% static 'css/home/responsive.css' %}">
       
       <!--Icon Fonts-->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
       
       
       <!-- Extras -->
       <link rel="stylesheet" type="text/css" href="{% static 'css/home/animate.css' %}">
       <link rel="stylesheet" type="text/css" href="{% static 'css/home/lightbox.css' %}">      
       
    {% endblock %}
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    
   
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body  data-spy="scroll" data-offset="20" data-target="#navbar">
 <!-- Nav Menu Section -->
    <div class="logo-menu">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation" data-spy="affix" data-offset-top="50">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header col-md-3">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home:home' %}"><i class="fa fa-briefcase"></i> Easy Law</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'account_logout'%}"><i class="fa fa-sign-out" aria-hidden="true"></i>Выйти</a></li>
                {% else %}
                    <li><a href="{% url 'account_signup'%}"><i class="fa fa-user-plus" aria-hidden="true"></i> Регистрация</a></li>
                    <li><a href="{% url 'account_login'%}"><i class="fa fa-sign-in" aria-hidden="true"></i> Войти</a></li>
                {% endif %}
                
            </ul>
        </div>
      </div>
    </nav>
    </div>
<!-- Nav Menu Section End -->

{% block application %}
{% endblock %}
{% bootstrap_javascript %}
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter42346704 = new Ya.Metrika({
                    id:42346704,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/42346704" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>