blank/blank/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
]

blank/cabinet/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url('^$', views.categories, name='categories'),
    url('^category/(?P<category_id>\d+)/$', views.category, name='category'),
    url('^blank/(?P<category_id>\d+)/(?P<blank_id>\d+)/$', views.blank, name='blank'),
    url('^download/$', views.download, name='download'),
    url('^bookmark/$', views.bookmark, name='bookmark'),
    url('^bookmark_add/$', views.bookmark_add, name='bookmark_add'),
    url('^profile/$', views.profile, name='profile'),
    
]

blank/home/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url('^$', views.home, name='home'),
]

blank/cabinet/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.
class Category(models.Model):
    ''' Категории бланков '''
    title = models.CharField('Название категории', max_length=200)
    description = models.TextField('Описание', null=True, blank=True)
    date_added = models.DateTimeField('Дата добавления', auto_now_add=True)
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['date_added']
    
    def __str__(self):
        return self.title
    
class Blank(models.Model):
    ''' Бланк документа '''
    category = models.ForeignKey(Category, verbose_name='Категория')
    title = models.CharField('Название бланка', max_length=200)
    description = models.TextField('Описание', null=True, blank=True)
    text = models.TextField('Текст бланка', null=True, blank=True)
    date_added = models.DateTimeField('Дата добавления', auto_now_add=True)
    
    class Meta:
        verbose_name = 'Бланк'
        verbose_name_plural = 'Бланки'
        ordering = ['date_added']
    
    def __str__(self):
        return self.title

class Bookmark(models.Model):
    ''' Закладки '''
    user = models.ForeignKey(User, verbose_name='Пользователь')
    blank = models.ForeignKey(Blank, verbose_name='Бланк')
    date_added = models.DateTimeField('Дата добавления',  auto_now_add=True)
    
    class Meta:
        verbose_name = 'Закладка'
        verbose_name_plural = 'Закладки'
        ordering = ['-date_added']
    
    def fullname(self):
        return self.user.get_full_name()
    
    fullname.short_description = 'Имя и Фамилия'
    fullname.allow_tags = True
    
    def __str__(self):
        return '{} {}'.format(self.user, self.blank)


    
class Comment(models.Model):
    ''' Комментарии текущего бланка '''
    author = models.ForeignKey(User, verbose_name='Автор комментария')
    blank = models.ForeignKey(Blank, verbose_name='Название бланка')
    date_added = models.DateTimeField('Дата добавления', auto_now_add=True)
    body = models.TextField('Текст')
    
    
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-date_added']

    def fullname(self):
        return self.author.get_full_name()
    
    fullname.short_description = 'Имя и Фамилия'
    fullname.allow_tags = True
    
    def __str__(self):
        return '{} {}: {}'.format(self.author.first_name, self.author.last_name, self.body)
    
    

blank/cabinet/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from allauth.account.forms import LoginForm
from .models import Comment

class FormDownload(forms.Form):
    '''Скачать бланк'''
    title = forms.CharField(widget=forms.HiddenInput())
    blank = forms.CharField(widget=forms.HiddenInput())
    

#
class SignupForm(forms.ModelForm):
    '''Регистрация Пользователя '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Логин"
        self.fields['username'].widget.attrs['placeholder'] = 'Логин'
    
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email']
        labels = {}
        widgets = {
            'first_name': forms.TextInput(attrs={'required': True, 'autofocus':'autofocus'}),
            'last_name': forms.TextInput(attrs={'required': True}),
        }

    def signup(self, request, user):
        user.save()

class LoginForm(LoginForm):
    '''Вход в личный кабинет'''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['login'].label = "Логин или e-mail"
        self.fields['login'].widget.attrs['placeholder'] = 'Логин или e-mail'

class UpdateProfileForm(forms.ModelForm):
    '''Обновление анкеты в личном кабинете'''
    class Meta:
        fields = ['first_name', 'last_name']
        model = User
    
class CommentForm(forms.ModelForm):
    ''' Комментарии в бланках '''
    class Meta:
        model = Comment
        fields = ['body']
        labels = {'body': 'Ваш комментарий'}
    
    

blank/cabinet/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from weasyprint import HTML
from io import BytesIO
from django.http import HttpResponse, JsonResponse, Http404
from .models import Category, Blank, Bookmark
from .translit import translit
from .forms import FormDownload, UpdateProfileForm, CommentForm


# Create your views here.
@login_required
def categories(request):
    ''' Список всех категорий '''
    categories = Category.objects.order_by('date_added')
    context = {
        'title': 'Категории',
        'categories': categories
    }
    return render(request, 'cabinet/categories.html', context)

@login_required
def category(request, category_id):
    ''' Описание и список всех бланков текущей категории '''
    category = get_object_or_404(Category, id=category_id)
    blanks = category.blank_set.order_by('date_added')
    context = {
        'title': category,
        'category': category,
        'blanks': blanks
    }
    return render(request, 'cabinet/category.html', context)

@login_required
def blank(request, category_id, blank_id):
    ''' Бланк для скачивания '''
    try:
        blank = Blank.objects.filter(category_id=category_id, id=blank_id).get()
    except Blank.DoesNotExist:
        raise Http404
    try:
        bookmark = Bookmark.objects.filter(user=request.user, blank=blank).get()
    except Bookmark.DoesNotExist:
        bookmark = None
        
    form = FormDownload(initial={'title': blank, 'blank': blank.text})
    
    if request.method != 'POST':
        comment_form = CommentForm()
    else:
        comment_form= CommentForm(data=request.POST)
        if comment_form.is_valid():
            author = request.user
            body = comment_form.cleaned_data['body'].strip()
            if len(body) == 0:
                return JsonResponse({'status':'error', 'message': 'Ошибка, заполните данные!'})
            new_comment = blank.comment_set.create(author=author, blank=blank, body=body)
           
            html_comment_add = get_template('cabinet/comment_add.html')
            html_comment_add = html_comment_add.render({'comment': new_comment})
            count = blank.comment_set.count()
            return JsonResponse({
                'status':'success',
                'message': 'Комментарий успешно добавлен!',
                'body': html_comment_add,
                'count': count
                })
        else:
            return JsonResponse({'status':'error', 'message': 'Ошибка, заполните данные!'})
    context = {
        'title': blank,
        'blank': blank,
        'bookmark': bookmark,
        'form': form,
        'comment_form': comment_form
    }
    return render(request, 'cabinet/blank.html', context)

@login_required
def bookmark(request):
    ''' Список закладок '''
    bookmarks = Bookmark.objects.filter(user=request.user)
    context={
        'title': 'Закладки',
        'bookmarks': bookmarks
    }
    return render(request, 'cabinet/bookmark.html', context)

@login_required
def bookmark_add(request):
    ''' Добавить или удалить с закладки '''
    blank_id = request.GET.get('blank_id')
    if blank_id:
        try:
            blank = Blank.objects.get(id=blank_id)
        except Blank.DoesNotExist:
            return JsonResponse({'status': 'error', 'message':'Операция не возможна т.к. нет такой записи в бд.'})

        bookmark_count = Bookmark.objects.filter(user=request.user, blank=blank).count()
        if bookmark_count > 0:
            deleted_bookmark = Bookmark.objects.filter(user=request.user, blank=blank).delete()
            return JsonResponse({
                'status': 'success',
                'method': 'Добавить в закладки',
                'message':'Удалено с закладки: "{}"'.format(blank.title)
            })
        else:
            new_bookmark = Bookmark.objects.create(user=request.user, blank=blank)
            return JsonResponse({
                'status': 'success',
                'method': 'Удалить с закладки',
                'message':'Добавлено в закладки: "{}"'.format(new_bookmark.blank)
            })
           
    return HttpResponse('dd')

@login_required
def download(request):
    ''' Скачать бланк в формате pdf '''
    if request.method == 'POST':
        form = FormDownload(data=request.POST)
        if form.is_valid():
            context = {
                'title': form.cleaned_data['title'],
                'blank': form.cleaned_data['blank'],
            }
            # Получаем документ в html формате
            html_data = get_template('cabinet/download.html')
            html_data = html_data.render(context)
            # Генерируем в pdf формат
            bytes_io = BytesIO()
            pdf_generator = HTML(string=html_data)
            pdf_generator.write_pdf(bytes_io)
            response = HttpResponse(content_type='application/pdf')
            filename = '{}.pdf'.format(translit(context['title']))
            response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
            pdf_data = bytes_io.getvalue()
            bytes_io.close()
            response.write(pdf_data)
            return response
    return HttpResponse('')

@login_required
def profile(request):
    ''' Редактирование профиля '''
    success = ''
    if request.method != 'POST':
        form = UpdateProfileForm(instance=request.user)
    else:
        form = UpdateProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            success = 'Ваш профиль успешно изменен!'
    context = {
        'title': 'Профиль',
        'form': form,
        'success': success
    }
    return render(request, 'cabinet/profile.html', context)

blank/templates/cabinet/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{{title}}{% endblock %}</title>
    <meta charset="utf-8">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    {% bootstrap_css %}
    {% block css %}{% endblock %}
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/cabinet/style.css' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'cabinet:categories' %}"><i class="fa fa-briefcase"></i>Личный кабинет</a>
            </div>
            
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'cabinet:bookmark' %}"><i class="fa fa-bookmark" aria-hidden="true"></i>Закладки</a></li>
                    <li><a href="{% url 'cabinet:profile' %}"><i class="fa fa-user" aria-hidden="true"></i>Профиль</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'account_logout'%}"><i class="fa fa-sign-out" aria-hidden="true"></i>Выйти</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
    
        </div><!-- /.container-fluid -->
    </div>
</nav>
<div class="logo">
    <a href="{% url 'cabinet:categories' %}"><img src="{% static 'images/logo.png' %}" alt=""></a>
</div>
<div class="container">
    <div class="row">
        <nav class="col col-sm-3">
            <ul class="vertical-menu">
                {% for category in nav_categories %}
                    {% if category_id == category.id %}
                        <li><a class="active" href="{% url 'cabinet:category' category.id %}">{{category.title}}</a></li>
                    {% else %}
                        <li><a href="{% url 'cabinet:category' category.id %}">{{category.title}}</a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </nav>
        <div class="col col-sm-9">
            {% block application %}
            {% endblock %}
        </div>
    </div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col col-xs-12">
                <p>&copy; easylaw.1rpi.ru</p>
            </div>
        </div>
    </div>
</footer>
{% bootstrap_javascript %}
{% block js %}{% endblock %}
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter42346704 = new Ya.Metrika({
                    id:42346704,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/42346704" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>
</html>