blank/blank/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
]

blank/cabinet/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url('^$', views.categories, name='categories'),
    url('^category/(?P<category_id>\d+)/$', views.category, name='category'),
    url('^blank/(?P<category_id>\d+)/(?P<blank_id>\d+)/$', views.blank, name='blank'),
    url('^download/$', views.download, name='download'),
    url('^bookmark/$', views.bookmark, name='bookmark'),
    url('^bookmark_add/$', views.bookmark_add, name='bookmark_add'),
    url('^profile/$', views.profile, name='profile'),
    
]

blank/home/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url('^$', views.home, name='home'),
]

blank/cabinet/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.
class Category(models.Model):
    ''' Категории бланков '''
    title = models.CharField('Название категории', max_length=200)
    description = models.TextField('Описание', null=True, blank=True)
    date_added = models.DateTimeField('Дата добавления', auto_now_add=True)
    
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['date_added']
    
    def __str__(self):
        return self.title
    
class Blank(models.Model):
    ''' Бланк документа '''
    category = models.ForeignKey(Category, verbose_name='Категория')
    title = models.CharField('Название бланка', max_length=200)
    description = models.TextField('Описание', null=True, blank=True)
    text = models.TextField('Текст бланка', null=True, blank=True)
    date_added = models.DateTimeField('Дата добавления', auto_now_add=True)
    
    class Meta:
        verbose_name = 'Бланк'
        verbose_name_plural = 'Бланки'
        ordering = ['date_added']
    
    def __str__(self):
        return self.title

class Bookmark(models.Model):
    ''' Закладки '''
    user = models.ForeignKey(User, verbose_name='Пользователь')
    blank = models.ForeignKey(Blank, verbose_name='Бланк')
    date_added = models.DateTimeField('Дата добавления',  auto_now_add=True)
    
    class Meta:
        verbose_name = 'Закладка'
        verbose_name_plural = 'Закладки'
        ordering = ['-date_added']
    
    def fullname(self):
        return self.user.get_full_name()
    
    fullname.short_description = 'Имя и Фамилия'
    fullname.allow_tags = True
    
    def __str__(self):
        return '{} {}'.format(self.user, self.blank)


    
class Comment(models.Model):
    ''' Комментарии текущего бланка '''
    author = models.ForeignKey(User, verbose_name='Автор комментария')
    blank = models.ForeignKey(Blank, verbose_name='Название бланка')
    date_added = models.DateTimeField('Дата добавления', auto_now_add=True)
    body = models.TextField('Текст')
    
    
    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-date_added']

    def fullname(self):
        return self.author.get_full_name()
    
    fullname.short_description = 'Имя и Фамилия'
    fullname.allow_tags = True
    
    def __str__(self):
        return '{} {}: {}'.format(self.author.first_name, self.author.last_name, self.body)
    
    

blank/cabinet/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from allauth.account.forms import LoginForm
from .models import Comment

class FormDownload(forms.Form):
    '''Скачать бланк'''
    title = forms.CharField(widget=forms.HiddenInput())
    blank = forms.CharField(widget=forms.HiddenInput())
    

#
class SignupForm(forms.ModelForm):
    '''Регистрация Пользователя '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Логин"
        self.fields['username'].widget.attrs['placeholder'] = 'Логин'
    
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email']
        labels = {}
        widgets = {
            'first_name': forms.TextInput(attrs={'required': True, 'autofocus':'autofocus'}),
            'last_name': forms.TextInput(attrs={'required': True}),
        }

    def signup(self, request, user):
        user.save()

class LoginForm(LoginForm):
    '''Вход в личный кабинет'''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['login'].label = "Логин или e-mail"
        self.fields['login'].widget.attrs['placeholder'] = 'Логин или e-mail'

class UpdateProfileForm(forms.ModelForm):
    '''Обновление анкеты в личном кабинете'''
    class Meta:
        fields = ['first_name', 'last_name']
        model = User
    
class CommentForm(forms.ModelForm):
    ''' Комментарии в бланках '''
    class Meta:
        model = Comment
        fields = ['body']
        labels = {'body': 'Ваш комментарий'}
    
    

blank/cabinet/views.py
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from weasyprint import HTML
from io import BytesIO
from django.http import HttpResponse, JsonResponse, Http404
from .models import Category, Blank, Bookmark
from .translit import translit
from .forms import FormDownload, UpdateProfileForm, CommentForm


# Create your views here.
@login_required
def categories(request):
    ''' Список всех категорий '''
    categories = Category.objects.order_by('date_added')
    context = {
        'title': 'Категории',
        'categories': categories
    }
    return render(request, 'cabinet/categories.html', context)

@login_required
def category(request, category_id):
    ''' Описание и список всех бланков текущей категории '''
    category = get_object_or_404(Category, id=category_id)
    blanks = category.blank_set.order_by('date_added')
    context = {
        'title': category,
        'category': category,
        'blanks': blanks
    }
    return render(request, 'cabinet/category.html', context)

@login_required
def blank(request, category_id, blank_id):
    ''' Бланк для скачивания '''
    try:
        blank = Blank.objects.filter(category_id=category_id, id=blank_id).get()
    except Blank.DoesNotExist:
        raise Http404
    try:
        bookmark = Bookmark.objects.filter(user=request.user, blank=blank).get()
    except Bookmark.DoesNotExist:
        bookmark = None
        
    form = FormDownload(initial={'title': blank, 'blank': blank.text})
    
    if request.method != 'POST':
        comment_form = CommentForm()
    else:
        comment_form= CommentForm(data=request.POST)
        if comment_form.is_valid():
            author = request.user
            body = comment_form.cleaned_data['body'].strip()
            if len(body) == 0:
                return JsonResponse({'status':'error', 'message': 'Ошибка, заполните данные!'})
            new_comment = blank.comment_set.create(author=author, blank=blank, body=body)
           
            html_comment_add = get_template('cabinet/comment_add.html')
            html_comment_add = html_comment_add.render({'comment': new_comment})
            count = blank.comment_set.count()
            return JsonResponse({
                'status':'success',
                'message': 'Комментарий успешно добавлен!',
                'body': html_comment_add,
                'count': count
                })
        else:
            return JsonResponse({'status':'error', 'message': 'Ошибка, заполните данные!'})
    context = {
        'title': blank,
        'blank': blank,
        'bookmark': bookmark,
        'form': form,
        'comment_form': comment_form
    }
    return render(request, 'cabinet/blank.html', context)

@login_required
def bookmark(request):
    ''' Список закладок '''
    bookmarks = Bookmark.objects.filter(user=request.user)
    context={
        'title': 'Закладки',
        'bookmarks': bookmarks
    }
    return render(request, 'cabinet/bookmark.html', context)

@login_required
def bookmark_add(request):
    ''' Добавить или удалить с закладки '''
    blank_id = request.GET.get('blank_id')
    if blank_id:
        try:
            blank = Blank.objects.get(id=blank_id)
        except Blank.DoesNotExist:
            return JsonResponse({'status': 'error', 'message':'Операция не возможна т.к. нет такой записи в бд.'})

        bookmark_count = Bookmark.objects.filter(user=request.user, blank=blank).count()
        if bookmark_count > 0:
            deleted_bookmark = Bookmark.objects.filter(user=request.user, blank=blank).delete()
            return JsonResponse({
                'status': 'success',
                'method': 'Добавить в закладки',
                'message':'Удалено с закладки: "{}"'.format(blank.title)
            })
        else:
            new_bookmark = Bookmark.objects.create(user=request.user, blank=blank)
            return JsonResponse({
                'status': 'success',
                'method': 'Удалить с закладки',
                'message':'Добавлено в закладки: "{}"'.format(new_bookmark.blank)
            })
           
    return HttpResponse('dd')

@login_required
def download(request):
    ''' Скачать бланк в формате pdf '''
    if request.method == 'POST':
        form = FormDownload(data=request.POST)
        if form.is_valid():
            context = {
                'title': form.cleaned_data['title'],
                'blank': form.cleaned_data['blank'],
            }
            # Получаем документ в html формате
            html_data = get_template('cabinet/download.html')
            html_data = html_data.render(context)
            # Генерируем в pdf формат
            bytes_io = BytesIO()
            pdf_generator = HTML(string=html_data)
            pdf_generator.write_pdf(bytes_io)
            response = HttpResponse(content_type='application/pdf')
            filename = '{}.pdf'.format(translit(context['title']))
            response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
            pdf_data = bytes_io.getvalue()
            bytes_io.close()
            response.write(pdf_data)
            return response
    return HttpResponse('')

@login_required
def profile(request):
    ''' Редактирование профиля '''
    success = ''
    if request.method != 'POST':
        form = UpdateProfileForm(instance=request.user)
    else:
        form = UpdateProfileForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            success = 'Ваш профиль успешно изменен!'
    context = {
        'title': 'Профиль',
        'form': form,
        'success': success
    }
    return render(request, 'cabinet/profile.html', context)

blank/cabinet/templates/cabinet/blank.html
{% extends 'cabinet/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load strip %}
{% block js %}
    <script src="{% static 'js/cabinet/jquery.ns-autogrow.min.js' %}"></script>
    <script>
        var blank_id = {{blank.id}};
    </script>
    <script src="{% static 'js/cabinet/blank.js' %}"></script>
    
{% endblock %}
{% block application %}
<div class="row">
    <div class="col col-xs-12">
        <h2 class="text-center">{{blank.title}}</h2>
        <hr>
        {% if blank.description|default_if_none:''|strip %}
            {{blank.description|safe}}
            <hr>
        {% endif %}
        
        {% if blank.text|default_if_none:''|strip %}
        <div id="content-blank">
            {{blank.text|safe}}
        </div>
        <form id="form-blank" method="POST" action="{% url 'cabinet:download' %}">
            {% csrf_token %}
            {{form.as_p}}
            {% buttons %}
                {% if bookmark %}
                    <a class="btn btn-save" id="bookmark-add" href="#"><i class="fa fa-bookmark" aria-hidden="true"></i> Удалить c закладки</a> 
                {% else %}
                    <a class="btn btn-save" id="bookmark-add" href="#"><i class="fa fa-bookmark" aria-hidden="true"></i> Добавить в закладки</a>
                {% endif %}
                <button type="submit" class="btn btn-save"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> Сохранить документ</button>
            {% endbuttons %}
        </form>
        {% endif %}
        <hr>
        <h4>Комментарии: <span id="comment-count">{{blank.comment_set.count}}</span></h4>
        <form id="form-comment" method="POST" action="" novalidate>
            {% csrf_token %}
            {% bootstrap_field  comment_form.body %}
            <button type="submit" class="btn btn-save" disabled="disabled">Добавить комментарий</button>
        </form>
        <div class="comments">
            {% for comment in blank.comment_set.all %}
                <div class="comment">
                    <p class="author">{{comment.author.get_full_name}} - <span class="date">{{comment.date_added}}</span></p>
                    {{comment.body|linebreaks}}
                </div>
            {% endfor %}
        </div>
    </div>
    
</div>
<div id="snackbar"></div>
{% endblock %}

blank/cabinet/templates/cabinet/bookmark.html
{% extends 'cabinet/base.html' %}
{% load strip %}
{% block application %}
<div class="row">
    <div class="col col-xs-12">
        <h3>Закладки</h3>
        <hr>
        
        {% if bookmarks|length > 0%}
            <div class="table-responsive">
                <table class="table table-bordered table-hover ">
                    <thead>
                        <tr>
                            <th class="text-center">Список документов</th>
                            <th class="text-center">Контент</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bookmark in bookmarks %}
                            <tr>
                                <td>{{bookmark.blank.title}}</td>
                                <td><a href="{% url 'cabinet:blank' bookmark.blank.category.id bookmark.blank.id %}">Показать</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        {% else %}
            <p>Нет добавленных закладок</p>
        {% endif %}        
    </div>
</div>
{% endblock %}

blank/cabinet/templates/cabinet/categories.html
{% extends 'cabinet/base.html' %}

{% block application %}

<div class="row">
    <div class="col col-xs-12">
        {% if categories|length > 0%}
            <div class="table-responsive">
                <table class="table table-bordered table-hover ">
                    <thead>
                        <tr>
                            <th class="text-center">Категории</th>
                            <th class="text-center">Контент</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for category in categories %}
                            <tr>
                                <td>{{category.title}}</td>
                                <td><a href="{% url 'cabinet:category' category.id %}">Показать</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        {% else %}
            <p>Нет добавленных категории</p>
        {% endif %}        
    </div>
</div>

{% endblock %}

blank/cabinet/templates/cabinet/category.html
{% extends 'cabinet/base.html' %}
{% load strip %}
{% block application %}
<div class="row">
    <div class="col col-xs-12">
        {% if category.description|default_if_none:''|strip %}
            {{category.description|safe}}
            <hr>
        {% endif %}
        
        {% if blanks|length > 0%}
            <div class="table-responsive">
                <table class="table table-bordered table-hover ">
                    <thead>
                        <tr>
                            <th class="text-center">Список документов</th>
                            <th class="text-center">Контент</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for blank in blanks %}
                            <tr>
                                <td>{{blank.title}}</td>
                                <td><a href="{% url 'cabinet:blank' category.id blank.id %}">Показать</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        {% else %}
            <p>Нет добавленных бланков в текущей категории</p>
        {% endif %}        
    </div>
</div>
{% endblock %}

blank/cabinet/templates/cabinet/comment_add.html
<div class="comment">
    <p class="author">{{comment.author.get_full_name}} - <span class="date">{{comment.date_added}}</span></p>
    {{comment.body|linebreaks}}
</div>

blank/cabinet/templates/cabinet/download.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/cabinet/blank_print.css' %}"
    </head>
    
    <body>
        {{blank|safe}}
    </body>
</html>

blank/cabinet/templates/cabinet/index.html
{% extends 'cabinet/base.html' %}

{% block application %}

{% endblock %}

blank/cabinet/templates/cabinet/profile.html
{% extends 'cabinet/base.html' %}
{% load static %}
{% load bootstrap3 %}
{% block application %}
<div class="row">
    <div class="col col-xs-12">
        <h1 class="text-center">{{title}}</h1>
        <hr>
        {% if success %}
            <div class="alert alert-success">
                 <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{success}}
            </div>
        {% endif %}
        <form id="form-blank" method="POST" action="{% url 'cabinet:profile' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-save">Сохранить</button>
            {% endbuttons %}
        </form>
    </div>
</div>
<div id="snackbar">Заполните все данные текущего документа</div>
{% endblock %}